### PR TITLE
jQuery slim-compatible Staticman JS script

### PR DESCRIPTION
**Pull request by VincentTam**
# Problem

Hi this is a contributor of Beautiful Jekyll('s Staticman integration developed by <span>@</span>mmistakes).

:warning: From daattali/beautiful-jekyll<span>#</span>766, we see that `ajax` isn't present in the slim version of jQuery.

https://github.com/fahimscirex/fahimscirex.github.io/blob/dd39d1d41d904e3d0b172077f1a8545dc624cf63/assets/js/staticman.js#L18
https://github.com/fahimscirex/fahimscirex.github.io/blob/dd39d1d41d904e3d0b172077f1a8545dc624cf63/_includes/staticman-comments.html#L78

# Description

Unmerged daattali/beautiful-jekyll#782 that I've recently submitted

### CODE REVIEW

**Comment by fahimscirex** [comment]
@VincentTam thanks for the fix. But I'm still facing error. Can you help me find out the problem? Is it the path destination or API instance?

**Comment by VincentTam** [comment]
> @VincentTam thanks for the fix. But I'm still facing error. Can you help me find out the problem? Is it the path destination or API instance?

@fahimscirex Can you describe your error?

**Comment by fahimscirex** [comment]
@VincentTam  I get this error message when I try to comment.
Screenshot from 2021-02-18 08-33-19

**Comment by VincentTam** [comment]
@fahimscirex It seems to be a server-side error.  You may try web browser's web dev tool for investigation.

> Access to XMLHttpRequest at 'https:<span>//staticman-scirex.herokuapp.com/</span>v3/entry/github/fahimscirex/fahimscirex.github.io/gh-pages/comments' from origin 'https://fahimscirex.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

> POST https<span>://staticman-scirex.herokuapp.com/v3/entry/github/</span>fahimscirex/fahimscirex.github.io/gh-pages/comments net::ERR_FAILED

The error message is the same as that of eduardoboucas/staticman#278, which turned out to be a problem of the API instance.

Request Header

~~~
POST /v3/entry/github/fahimscirex/fahimscirex.github.io/gh-pages/comments HTTP/1.1
Host: staticman-scirex.herokuapp.com
Connection: keep-alive
Content-Length: 299
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 OPR/71.0.3770.198
X-Requested-With: XMLHttpRequest
Content-Type: application/x-www-form-urlencoded
Accept: */*
Origin: https://fahimscirex.github.io
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://fahimscirex.github.io/post/purono-koutuk-book-review/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,fr;q=0.8
~~~

It seems to me that the naming of the branch is irrelevant, but the source code for a user's GH page is supposed to be on `master`.  I'm not sure if that caused GH Pages error.

https://github.com/fahimscirex/fahimscirex.github.io/blob/d38288dd3ec537709a2d6b67d36d335a161bd921/staticman.yml#L24-L28

**Pull request merged**
